{% set version = "3.9.3" %}

package:
  name: stack
  version: {{ version }}

source:
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux64]
  sha256: bc45cf6e1d00910348dcceb510a469056f6d9c63997230f901c22cf997598b05  # [linux64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-aarch64.tar.gz  # [linux and aarch64]
  sha256: c94360be1fe851c6e9f82089e93c8a4937ca536d42abccac908749e5a74220aa  # [linux and aarch64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx and 64]
  sha256: e9139c80dc0e2d5df6bef45d40e20c8ac9ca2dbd1bb31358782fa5446d0df38c  # [osx and 64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-aarch64.tar.gz  # [osx and arm64]
  sha256: 2e3b49767a41b9238afd9e2fa62f79860b2993b186db89debcd259e3a608955d  # [osx and arm64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: f7452f2e01e5bf37fb136685ea02b776d11c2ed693524fc4ff0d0b00075c28de  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cxx') }}  # [linux]
    # Needed to bump libc version on aarch64 (see conda-forge.yml and recipe/conda_build_config.yaml):
    - {{ stdlib('c') }}      # [linux and aarch64]
    - gmp                    # [linux]
    - make                   # [linux]
    - ncurses                # [linux]
    - perl                   # [linux]

about:
  home: www.haskellstack.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
    - matthiasdiener
