{% set version = "3.9.1" %}

package:
  name: stack
  version: {{ version }}

source:
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux64]
  sha256: c4816581c445f6e4d43bf7ce6064b0d58d136e49c45e6336d612c4d8eaaedd11  # [linux64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-aarch64.tar.gz  # [linux and aarch64]
  sha256: 9173e51a3e7c96b7b87e51efe1441cdef76276a7ec0256937eae2c1713fb6195  # [linux and aarch64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx and 64]
  sha256: 461b6761cc458607c97dffa7155c8f8f6d7108a83cf31f82ac5afe2d120bcaf1  # [osx and 64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-aarch64.tar.gz  # [osx and arm64]
  sha256: e0265e2816bbec0fd852b87ebdab4c37aae55985c40bc155d94c1abe64af0d75  # [osx and arm64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: 1a922d6fa0f0b85a2eacc30a5fd71118ad93ca03038c70abd71b238866587fd8  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cxx') }}  # [linux]
    # Needed to bump libc version on aarch64 (see conda-forge.yml and recipe/conda_build_config.yaml):
    - {{ stdlib('c') }}      # [linux and aarch64]
    - gmp                    # [linux]
    - make                   # [linux]
    - ncurses                # [linux]
    - perl                   # [linux]

about:
  home: www.haskellstack.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
    - matthiasdiener
