{% set version = "1.3.2" %}
{% set unixsha256 = "ebeb76744c85b7cd5504b6e29f8912b920a247b7895a2d4a1fe9564f5c5ec164" %}
{% set osxsha256 = "e7097282684d182d8fecc4990178e91fd7efe83f33827b4d066fb7324e2d7dd9" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [unix]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64-static.tar.gz  # [unix]
  sha256: {{ unixsha256 }}  # [unix]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]

build:
  number: 1
  skip: True  # [win] 

requirements:
  run:
    - gmp >=5.0.1,<7

test:
  commands:
    - stack --help

about:
  home: www.haskellstack.org
  license: BSD3-like
  summary: 'Stack is a cross-platform program for developing Haskell projects.'
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
