{% set version = "3.11.1" %}

package:
  name: stack
  version: {{ version }}

source:
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux64]
  sha256: 1fda71e657cd8d355625cc66b61b352699279dfee2664c014a392163bd19a952  # [linux64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-aarch64.tar.gz  # [linux and aarch64]
  sha256: 1617ae9976a5cd38ad4daec583b026b589eb45d5482afb045cd4ca8c8d0de6d0  # [linux and aarch64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx and 64]
  sha256: 603db63eef6246b02dd042e446686f61e3410ee9ef73cb3838314e24468fb290  # [osx and 64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-aarch64.tar.gz  # [osx and arm64]
  sha256: 652572ddf74616a7975892de9c61a9e5e6b5979db4f9b00fcd659ac6a15d7330  # [osx and arm64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: 741acd147cfba542980f5f5377eab9ad31eb446c5bda195608dd276ad242be51  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cxx') }}  # [linux]
    # Needed to bump libc version on aarch64 (see conda-forge.yml and recipe/conda_build_config.yaml):
    - {{ stdlib('c') }}      # [linux and aarch64]
    - gmp                    # [linux]
    - make                   # [linux]
    - ncurses                # [linux]
    - perl                   # [linux]

about:
  home: www.haskellstack.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
    - matthiasdiener
