{% set version = "2.7.1" %}
{% set linuxsha256 = "2bc47749ee4be5eccb52a2d4a6a00b0f3b28b92517742b40c675836d7db2777d" %}
{% set osxsha256 = "4248c6fbc87e8a2c06f39e867eb5ef28eae0d99470137cb415356c631c0dcbf2" %}
{% set winsha256 = "12729150cbbd0e5007fc59a70ed17a9ba4ef1430e24d3e440b435128a3029ab1" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: {{ linuxsha256 }}  # [linux]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}  # [linux]
    - gmp                  # [linux]
    - make                 # [linux]
    - ncurses              # [linux]
    - perl                 # [linux]

about:
  home: www.haskellstack.org
  license: BSD3-like
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
