{% set version = "2.5.1" %}
{% set linuxsha256 = "c83b6c93d6541c0bce2175085a04062020f4160a86116e20f3b343b562f2d1e8" %}
{% set osxsha256 = "f4aedfa8fbe371f77286ee97ec5c3c553842e7ae15b2952a8b8442dccba04bf0" %}
{% set winsha256 = "925fcc22e8f40465d2f6a5f9e23a49178d650bd8c6caa3d820c80258a8232a8b" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: {{ linuxsha256 }}  # [linux]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 1

requirements:
  run:
    - {{ compiler('c') }}  # [linux]
    - gmp                  # [linux]
    - make                 # [linux]
    - ncurses              # [linux]
    - perl                 # [linux]

about:
  home: www.haskellstack.org
  license: BSD3-like
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
