{% set version = "2.5.0.1" %}
{% set linuxsha256 = "0b229c10621dd80b70cf60b467878e0f4d12e0145a586d903e2f037376b874d3" %}
{% set osxsha256 = "93220f718a7c475bbdf7a8776e5e5e262329a6fe96229a7a91b934b038bf7763" %}
{% set winsha256 = "194fd4122020b654cb1c6604ab02a5b3fb536d0a6f4063f3b4e9528a087b817b" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: {{ linuxsha256 }}  # [linux]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 0

test:
  commands:
    - stack --version
    - stack --help
    - stack new helloworld new-template && cd helloworld && stack setup && stack build

about:
  home: www.haskellstack.org
  license: BSD3-like
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
