{% set version = "2.3.3" %}
{% set linuxsha256 = "e7329c75d9c7ea168eb12caa954102e451906f350604a18d6e852ac81da5a2be" %}
{% set osxsha256 = "3878029377275641b9e2b1dfe7fab819f1f18b3ffda6414ce07472b17c125c7f" %}
{% set winsha256 = "fb14dfea14cc0562a2e7c78f2c92be0f7b6119f1b3c2265f5e623b7149309802" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: {{ linuxsha256 }}  # [linux]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 0

test:
  commands:
    - stack --version
    - stack --help
    - stack new helloworld new-template && cd helloworld && stack setup && stack build

about:
  home: www.haskellstack.org
  license: BSD3-like
  license_file: LICENSE
  summary: 'Stack is a cross-platform program for developing Haskell projects.'
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
