{% set version = "2.9.3" %}
{% set linuxsha256 = "938f689dc45e2693ab1ca3ea215790b3786dfd531dcf6c0bf40842c24e579ae9" %}
{% set osxsha256 = "34b74a0e764cd7363255005158984be11faa392871acc6b5af3238ac444a2806" %}
{% set winsha256 = "9403e374429aaab4d8843d9ed1bb616f7c94bea81fee0f594412b8bbb6b98970" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: {{ linuxsha256 }}  # [linux]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}  # [linux]
    - gmp                  # [linux]
    - make                 # [linux]
    - ncurses              # [linux]
    - perl                 # [linux]

about:
  home: www.haskellstack.org
  license: BSD3-like
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
    - matthiasdiener
