{% set version = "2.1.3" %}
{% set unixsha256 = "c724b207831fe5f06b087bac7e01d33e61a1c9cad6be0468f9c117d383ec5673" %}
{% set osxsha256 = "84b05b9cdb280fbc4b3d5fe23d1fc82a468956c917e16af7eeeabec5e5815d9f" %}
{% set winsha256 = "075bcd9130cd437de4e726466e5738c92c8e47d5666aa3a15d339e6ba62f76b2" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [unix]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [unix]
  sha256: {{ unixsha256 }}  # [unix]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 0

requirements:
  host:
    - gmp  # [not win]
  run:
    - gmp  # [not win]

test:
  commands:
    - stack --help
    - stack new helloworld new-template && cd helloworld && stack setup && stack build

about:
  home: www.haskellstack.org
  license: BSD3-like
  license_file: LICENSE
  summary: 'Stack is a cross-platform program for developing Haskell projects.'
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
