{% set version = "2.7.5" %}
{% set linuxsha256 = "9bcd165358d4dcafd2b33320d4fe98ce72faaf62300cc9b0fb86a27eb670da50" %}
{% set osxsha256 = "94176b71425d76b94b088515103316ae1ff96d123344b1f4609c103d0d5bdcc4" %}
{% set winsha256 = "a77a1b27501d78800baa7e88d8ccca1d6e9b19b9c59f02f2a40ca260aaa75260" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux]
  sha256: {{ linuxsha256 }}  # [linux]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}  # [linux]
    - gmp                  # [linux]
    - make                 # [linux]
    - ncurses              # [linux]
    - perl                 # [linux]

about:
  home: www.haskellstack.org
  license: BSD3-like
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
