{% set version = "3.7.1" %}

package:
  name: stack
  version: {{ version }}

source:
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux64]
  sha256: b6df9168d471d917d955ee80553562ca2b0b3b1aa61cd1256199406c2d8c4eb4  # [linux64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-aarch64.tar.gz  # [linux and aarch64]
  sha256: 752321c6af6bc88960a086ebd9ede72937a567f312842a29deb2ddc9ab316a20  # [linux and aarch64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx and 64]
  sha256: 08cff579295b3cfd3f1c6bf4948d243c3a38eebff151554b3ada2d381e574486  # [osx and 64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-aarch64.tar.gz  # [osx and arm64]
  sha256: 9943acbcc791f474d8c68493082308509ec8a8f4603039cf0f7639293d13a233  # [osx and arm64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: 6a7afbd56f511bcd13553cfc8ce3329621d1648cf2c858cb45b4fc6a9158d992  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}    # [linux]
    - {{ compiler('cxx') }}  # [linux]
    # Needed to bump libc version on aarch64 (see conda-forge.yml and recipe/conda_build_config.yaml):
    - {{ stdlib('c') }}      # [linux and aarch64]
    - gmp                    # [linux]
    - make                   # [linux]
    - ncurses                # [linux]
    - perl                   # [linux]

about:
  home: www.haskellstack.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
    - matthiasdiener
