{% set version = "2.15.7" %}

package:
  name: stack
  version: {{ version }}

source:
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [linux64]
  sha256: d55f8554932aad23f7b1198e0d5ebe332073d73fe60e3f324d0b315c156d8c43  # [linux64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-aarch64.tar.gz  # [linux_aarch64]
  sha256: d55f8554932aad23f7b1198e0d5ebe332073d73fe60e3f324d0b315c156d8c43  # [linux_aarch64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx64]
  sha256: 1c17151516d120abdd9d6cdd93ba72ccda95db822da80bcafe0cf9cdc164c1d9  # [osx64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-aarch64.tar.gz  # [osx_arm64]
  sha256: 1c17151516d120abdd9d6cdd93ba72ccda95db822da80bcafe0cf9cdc164c1d9  # [osx_arm64]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: 419aa63fd8e93d241e2b41e981bbee0ca6129fb95f062b76bb7b2243bd70abf8  # [win]

build:
  number: 0

requirements:
  run:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - gmp                  # [linux]
    - make                 # [linux]
    - ncurses              # [linux]
    - perl                 # [linux]

about:
  home: www.haskellstack.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
    - LaurentRDC
    - matthiasdiener
