{% set version = "1.9.1" %}
{% set unixsha256 = "647306bbf65dd0b555486e2a32776ba1cfe0c8f380e31c6aa93abd452cb209ee" %}
{% set osxsha256 = "c70073f7548d48bf07b7fa076902db5e0d470a941a35c5998106297a7c614d63" %}
{% set winsha256 = "0261779ce3598747528547585e78c4e6ad72b70523c9ac3d5c684f2b16791af6" %}

package:
  name: stack
  version: {{ version }}

source:
  fn: stack-{{ version }}-linux-x86_64.tar.gz  # [unix]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-linux-x86_64.tar.gz  # [unix]
  sha256: {{ unixsha256 }}  # [unix]
  fn: stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-osx-x86_64.tar.gz  # [osx]
  sha256: {{ osxsha256 }}  # [osx]
  fn: stack-{{ version }}-windows-x86_64.zip  # [win]
  url: https://github.com/commercialhaskell/stack/releases/download/v{{ version }}/stack-{{ version }}-windows-x86_64.zip  # [win]
  sha256: {{ winsha256 }}  # [win]

build:
  number: 0

requirements:
  run:
    - gmp >=5.0.1,<7  # [not win]

test:
  commands:
    - stack --help

about:
  home: www.haskellstack.org
  license: BSD3-like
  summary: 'Stack is a cross-platform program for developing Haskell projects.'
  doc_url: https://docs.haskellstack.org/en/stable/README/
  dev_url: https://github.com/commercialhaskell/stack

extra:
  recipe-maintainers:
    - eggzilla
