travis:
  secure:
    BINSTAR_TOKEN: fDbNRJXtSfanjwR2fsUKl6jdRAw73XL50Mb0rAawJB+eIBKEDGIZi6c+ys4wNJ5wKrOrdgYDvxW0PVxxF2DunSysFIBev9icIr29FFdbcrpQVLN2hf7Y2ECx/k+1amRJ3atuax2hB1IqrCuj+AW9wycaCEukYVe9SdjjyX3G76hwXxWgNKaFZ6MrcTaIXSpkDGuvvI6Zm/Yq7cTx8b/p2OPOksn41nrAuRw2IYt1dJ0L9HKBLGD2KDY9myIJ/PX1maDLA85ejkKwBLZ2LEKgNpDeLo08NJZIkO1DCvrCJVOVoCw+KXw7x/AaIGGN69QDfgzSLgK7+aoz8bM6kGzqQjCQWpmIYMMcq9rTAw3HyLryC638u2NSOOPIdNp9kXR6HXxR+LvhudSmOaZ5Y4tvDkG3Q3ed5m2i9h7FfJ110pB2GHaMshkKf24sT+AIaOGDZAnLJ/qsRU0RJQFb8VJziDkvCFJqS4bxvIKb1hiM3+cAdQ3hxMMHjZAxghZu9vSBcw4HqO1VDTmgCmQc1KMVIk7AFQp+nkpHH1uE0v+/CyzKrgYH2KkfmZfvb1k09YO3Jd6lO/2ifbJqkp8TDrhUVXgcsWx8jtgQTxFwf0os3El8KWcl2d/2FraBf9rTl8eVZvNvaYiyalcMP416IMu2B9zY6bkmoMvFFztvNI/wqUo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
